name: CodeCov
on: 
  push:
    branches:
      - master
      - test_01
      - test_02

  pull_request:
    branches:
      - master
      - test_01
      - test_02
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.8'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8
    - name: 'generate report'
      run: |
        pip install coverage
        coverage run -m unittest
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        flags: unittests
        fail_ci_if_error: true